---
kind: pipeline
name: linux-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: dryrun
  pull: always
  image: plugins/docker:linux-amd64
  settings:
    cache_from: appleboy/nginx-image-resizer
    dockerfile: Dockerfile
    dry_run: true
    repo: appleboy/nginx-image-resizer
  when:
    event:
    - pull_request

- name: publish
  pull: always
  image: plugins/docker:linux-amd64
  settings:
    auto_tag: true
    cache_from: appleboy/nginx-image-resizer
    dockerfile: Dockerfile
    daemon_off: false
    password:
      from_secret: docker_password
    repo: appleboy/nginx-image-resizer
    username:
      from_secret: docker_username
  when:
    event:
      exclude:
      - pull_request

trigger:
  ref:
  - refs/heads/master
  - refs/pull/**
  - refs/tags/**
